name: Java CI

on: [workflow_dispatch, push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cache: [maven]
        distribution: [temurin]
        java: [17, 21, 23, 24-ea, 25-ea]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }} ${{ matrix.distribution }}
        uses: actions/setup-java@v4
        with:
          cache: ${{ matrix.cache }}
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Setup skip tests that require illegal reflective access ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: echo 'ARG_LINE=-D"excludedGroups=RequireIllegalAccess" -Xmx2048m -javaagent:${settings.localRepository}/net/bytebuddy/byte-buddy-agent/${byte-buddy.version}/byte-buddy-agent-${byte-buddy.version}.jar' >> $GITHUB_ENV
      - name: Setup skip tests that require illegal reflective access not ubuntu
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: echo 'ARG_LINE=-D"excludedGroups=TestcontainersTests,RequireIllegalAccess" -Xmx2048m -javaagent:${settings.localRepository}/net/bytebuddy/byte-buddy-agent/${byte-buddy.version}/byte-buddy-agent-${byte-buddy.version}.jar' >> $GITHUB_ENV
      - name: Test with Maven
        run: ./mvnw test -B -V  --no-transfer-progress -D"license.skip=true" -D"jacoco.skip=true" $ARG_LINE
